<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.305" />
  </ItemGroup>

  <ItemGroup>
    <None Update="public/addons/counterstrikesharp/plugins/FixRandomSpawn/gamedata/FixRandomSpawn.json" Link="gamedata/FixRandomSpawn.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="public/addons/counterstrikesharp/plugins/FixRandomSpawn/lang/*.json" Link="lang/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
